<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>py</string>
	</array>
	<key>name</key>
	<string>WLST</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>cd\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>currentTree\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>prompt\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pwd\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>connect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>disconnect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>createDomain\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>readTemplate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>writeDomain\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>closeTemplate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>readDomain\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>addTemplate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>updateDomain\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>closeDomain\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>writeTemplate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exit\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>deploy\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>distributeApplication\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getWLDM\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>loadApplication\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>redeploy\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>startApplication\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stopApplication\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>undeploy\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>updateApplication\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exportDiagnosticData\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exportDiagnosticDataFromServer\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>activate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>assign\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>assignAll\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cancelEdit\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>create\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>delete\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>encrypt\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>get\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getActivationTask\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>invoke\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>isRestartRequired\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>loadDB\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>loadProperties\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>save\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>set\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>setOption\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>showChanges\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>startEdit\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stopEdit\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>unassign\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>unassignAll\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>undo\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>validate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>addListener\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>configToScript\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dumpStack\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dumpVariables\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>find\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getConfigManager\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getMBean\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getMBI\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getPath\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>listChildTypes\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lookup\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ls\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>man\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>redirect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>removeListener\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>showListeners\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>startRecording\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>state\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stopRecording\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stopRedirect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>storeUserConfig\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>threadDump\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>viewMBean\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>writeIniFile\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>migrate\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>resume\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>shutdown\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>startServer\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>start\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>suspend\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmConnect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmDisconnect\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmEnroll\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmGenBootStartupProps\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmKill\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmLog\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nm\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmServerLog\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmServerStatus\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmStart\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nmVersion\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>startNodeManager\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>config\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>custom\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>domainConfig\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>do,mainRuntime\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>edit\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>jndi\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>runtime\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>serverConfig\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>serverRuntime\b</string>
			<key>name</key>
			<string>keyword.source.wlst</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wlst</string>
	<key>uuid</key>
	<string>e6299242-7c82-492d-838e-09c1fa4149cc</string>
</dict>
</plist>
